# fly.toml app configuration file generated for dealbrief-scanner on 2025-06-04T10:45:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dealbrief-scanner'
primary_region = 'sea'

[build]

[env]
  NODE_TLS_REJECT_UNAUTHORIZED = "0"

[processes]
  api            = "npx tsx apps/api-main/server.ts"
  scanner_worker = "npx tsx apps/workers/worker.ts"
  sync_worker    = "npm run start --prefix apps/sync-worker"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['api']

# Ensure worker processes stay running
[[services]]
  processes = ['scanner_worker']
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  processes = ['sync_worker']
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]] # VM for the API
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['api']

[[vm]] # VM for the security scanner worker
  memory = '1gb' # Scanner worker might be memory intensive
  cpu_kind = 'shared'
  cpus = 1
  processes = ['scanner_worker']

[[vm]] # VM for the sync worker
  memory = '512mb' # Sync worker is likely less memory intensive
  cpu_kind = 'shared'
  cpus = 1
  processes = ['sync_worker']
